#!/bin/bash

source ../common.sh

status=0
TIMEFORMAT="    %R seconds"

commands="k b t k4 s4 s5 pd"

function basic {
    echo "Running basic tests"
    dir=$IMOGEN_HOME/tests/modal/basic
    files=$(cd $dir; ls *.imo)
    for file in $files; do
        for cmd in $commands; do
            emit "$file : $cmd"
            if ! eval "imogen modal $cmd -proof $dir/$file &> /dev/null"; then
                echo " failed"
                status=1
            fi
        done
    done
    emit "\r"
}

function usage {
    echo "Usage: runtests"
}

if (( $# > 0 )); then
    sub=$1; shift
    case $sub in
        "help"|"-help")
            usage
            ;;
        "basic")
            basic
            ;;
        *)
            usage
            exit 1
            ;;
    esac
else
    basic
fi

exit $status
