#!/bin/bash

source ../common.sh

status=0
TIMEFORMAT="    %R seconds"

function basic {
    echo "Running basic tests"
    dir=$IMOGEN_HOME/tests/linear/basic
    files=$(cd $dir; ls *.imo)
    for file in $files; do
        emit "$file"
        if ! eval "imogen linear prove -proof $dir/$file &> /dev/null"; then
            echo " failed"
            status=1
        fi
    done
    emit "\r"
}

function usage {
    echo "Usage: runtests"
}

if (( $# > 0 )); then
    sub=$1; shift
    case $sub in
        "help"|"-help")
            usage
            ;;
        "basic")
            basic
            ;;
        *)
            usage
            exit 1
            ;;
    esac
else
    basic
fi

exit $status
